name: Test

# Controls when the action will run
on: 

  # Triggers the workflow on push or pull request events
  push:
  
  # Allows running this workflow manually from the action tab
  workflow_dispatch:
  
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  discordNotification:
    name: Discord Notification
    runs-on: ubuntu-latest
    steps:
    - name: Actions for Discord
      # You may pin to the exact commit or the version.
      # uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: 'github'
      uses: Ilshidur/action-discord@0.3.2
      with:
        args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
